[package]
name = "check-passwords"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-postgres = "0.7"
bcrypt = "0.10.1"
dotenv = "0.15.0"
futures = "0.3"
